### ISSUE TITLE
ComplexNet doesn't train properly on `mps`

### ISSUE THREAD

**Issue by amonroymz** [MultiX-Amsterdam/image-data-module#6]
When I run the training for the last model of the image data tutorial (the one with the MNIST dataset), it doesn't run properly, and the magnitude of the outputs and losses are very large:

![image](https://github.com/MultiX-Amsterdam/image-data-module/assets/149786124/1527d387-fd64-4a61-b490-0cc569097535)

![image](https://github.com/MultiX-Amsterdam/image-data-module/assets/149786124/b8a02ae9-02eb-4b6a-b4ad-e2c9a250b98f)

**Comment by yenchiah** [comment]
I deleted the code for the ComplexNet and rename the original `Net` to `ComplexNet `.
